from typing import List
from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from sqlalchemy import func

from .. import models, schemas, auth
from ..database import get_db

router = APIRouter(prefix="/vouchers", tags=["vouchers"])


@router.get("/profiles", response_model=List[schemas.VoucherProfileOut])
def list_profiles(
    db: Session = Depends(get_db), user: models.User = Depends(auth.get_current_user)
):
    # Every query starts with .filter(business_id == user.business_id).
    # That single line, repeated everywhere, IS the tenant wall.
    profiles = (
        db.query(models.VoucherProfile)
        .filter(models.VoucherProfile.business_id == user.business_id)
        .all()
    )
    out = []
    for p in profiles:
        available = (
            db.query(func.count(models.Voucher.id))
            .filter(
                models.Voucher.business_id == user.business_id,
                models.Voucher.profile_id == p.id,
                models.Voucher.sold == False,  # noqa: E712
            )
            .scalar()
        )
        item = schemas.VoucherProfileOut.model_validate(p)
        item.available_count = available or 0
        out.append(item)
    return out


@router.post("/profiles", response_model=schemas.VoucherProfileOut)
def create_profile(
    payload: schemas.VoucherProfileCreate,
    db: Session = Depends(get_db),
    user: models.User = Depends(auth.get_current_user),
):
    profile = models.VoucherProfile(business_id=user.business_id, **payload.model_dump())
    db.add(profile)
    db.commit()
    db.refresh(profile)
    out = schemas.VoucherProfileOut.model_validate(profile)
    out.available_count = 0
    return out


@router.post("/batch", response_model=dict)
def add_voucher_batch(
    payload: schemas.VoucherBatchCreate,
    db: Session = Depends(get_db),
    user: models.User = Depends(auth.get_current_user),
):
    """Bulk-add voucher codes to a profile's available stock (e.g. pasted
    from a MikroTik export, or generated by a bridge agent — see README)."""
    profile = (
        db.query(models.VoucherProfile)
        .filter(
            models.VoucherProfile.id == payload.profile_id,
            models.VoucherProfile.business_id == user.business_id,
        )
        .first()
    )
    if not profile:
        raise HTTPException(status_code=404, detail="Voucher profile not found")

    added = 0
    for code in payload.codes:
        code = code.strip()
        if not code:
            continue
        db.add(models.Voucher(business_id=user.business_id, profile_id=profile.id, code=code))
        added += 1
    db.commit()
    return {"added": added}


@router.get("/", response_model=List[schemas.VoucherOut])
def list_vouchers(
    profile_id: int = None,
    only_available: bool = True,
    db: Session = Depends(get_db),
    user: models.User = Depends(auth.get_current_user),
):
    q = db.query(models.Voucher).filter(models.Voucher.business_id == user.business_id)
    if profile_id:
        q = q.filter(models.Voucher.profile_id == profile_id)
    if only_available:
        q = q.filter(models.Voucher.sold == False)  # noqa: E712
    return q.order_by(models.Voucher.id).limit(500).all()
