"""initial schema

Revision ID: cdfd14bf12ef
Revises: 
Create Date: 2026-08-26 21:22:29.615021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdfd14bf12ef'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('plan', sa.String(), nullable=True),
    sa.Column('subscription_status', sa.String(), nullable=True),
    sa.Column('trial_ends_at', sa.DateTime(), nullable=True),
    sa.Column('paystack_customer_code', sa.String(), nullable=True),
    sa.Column('paystack_subscription_code', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_businesses_id'), 'businesses', ['id'], unique=False)
    op.create_table('agents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('commission_rate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agents_business_id'), 'agents', ['business_id'], unique=False)
    op.create_index(op.f('ix_agents_id'), 'agents', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_business_id'), 'users', ['business_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('voucher_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('cost_price', sa.Float(), nullable=True),
    sa.Column('duration_label', sa.String(), nullable=True),
    sa.Column('low_stock_threshold', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voucher_profiles_business_id'), 'voucher_profiles', ['business_id'], unique=False)
    op.create_index(op.f('ix_voucher_profiles_id'), 'voucher_profiles', ['id'], unique=False)
    op.create_table('commission_adjustments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commission_adjustments_agent_id'), 'commission_adjustments', ['agent_id'], unique=False)
    op.create_index(op.f('ix_commission_adjustments_business_id'), 'commission_adjustments', ['business_id'], unique=False)
    op.create_index(op.f('ix_commission_adjustments_id'), 'commission_adjustments', ['id'], unique=False)
    op.create_table('payouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payouts_agent_id'), 'payouts', ['agent_id'], unique=False)
    op.create_index(op.f('ix_payouts_business_id'), 'payouts', ['business_id'], unique=False)
    op.create_index(op.f('ix_payouts_id'), 'payouts', ['id'], unique=False)
    op.create_table('sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('profile_name', sa.String(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('is_credit', sa.Boolean(), nullable=True),
    sa.Column('voided', sa.Boolean(), nullable=True),
    sa.Column('voided_at', sa.DateTime(), nullable=True),
    sa.Column('void_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['voucher_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_business_id'), 'sales', ['business_id'], unique=False)
    op.create_index(op.f('ix_sales_id'), 'sales', ['id'], unique=False)
    op.create_table('debtors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(), nullable=False),
    sa.Column('customer_phone', sa.String(), nullable=True),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_debtors_business_id'), 'debtors', ['business_id'], unique=False)
    op.create_index(op.f('ix_debtors_id'), 'debtors', ['id'], unique=False)
    op.create_table('vouchers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('sold', sa.Boolean(), nullable=True),
    sa.Column('sold_sale_id', sa.Integer(), nullable=True),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['voucher_profiles.id'], ),
    sa.ForeignKeyConstraint(['sold_sale_id'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vouchers_business_id'), 'vouchers', ['business_id'], unique=False)
    op.create_index(op.f('ix_vouchers_code'), 'vouchers', ['code'], unique=False)
    op.create_index(op.f('ix_vouchers_id'), 'vouchers', ['id'], unique=False)
    op.create_index(op.f('ix_vouchers_profile_id'), 'vouchers', ['profile_id'], unique=False)
    op.create_table('debtor_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('debtor_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['debtor_id'], ['debtors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_debtor_payments_business_id'), 'debtor_payments', ['business_id'], unique=False)
    op.create_index(op.f('ix_debtor_payments_debtor_id'), 'debtor_payments', ['debtor_id'], unique=False)
    op.create_index(op.f('ix_debtor_payments_id'), 'debtor_payments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_debtor_payments_id'), table_name='debtor_payments')
    op.drop_index(op.f('ix_debtor_payments_debtor_id'), table_name='debtor_payments')
    op.drop_index(op.f('ix_debtor_payments_business_id'), table_name='debtor_payments')
    op.drop_table('debtor_payments')
    op.drop_index(op.f('ix_vouchers_profile_id'), table_name='vouchers')
    op.drop_index(op.f('ix_vouchers_id'), table_name='vouchers')
    op.drop_index(op.f('ix_vouchers_code'), table_name='vouchers')
    op.drop_index(op.f('ix_vouchers_business_id'), table_name='vouchers')
    op.drop_table('vouchers')
    op.drop_index(op.f('ix_debtors_id'), table_name='debtors')
    op.drop_index(op.f('ix_debtors_business_id'), table_name='debtors')
    op.drop_table('debtors')
    op.drop_index(op.f('ix_sales_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_business_id'), table_name='sales')
    op.drop_table('sales')
    op.drop_index(op.f('ix_payouts_id'), table_name='payouts')
    op.drop_index(op.f('ix_payouts_business_id'), table_name='payouts')
    op.drop_index(op.f('ix_payouts_agent_id'), table_name='payouts')
    op.drop_table('payouts')
    op.drop_index(op.f('ix_commission_adjustments_id'), table_name='commission_adjustments')
    op.drop_index(op.f('ix_commission_adjustments_business_id'), table_name='commission_adjustments')
    op.drop_index(op.f('ix_commission_adjustments_agent_id'), table_name='commission_adjustments')
    op.drop_table('commission_adjustments')
    op.drop_index(op.f('ix_voucher_profiles_id'), table_name='voucher_profiles')
    op.drop_index(op.f('ix_voucher_profiles_business_id'), table_name='voucher_profiles')
    op.drop_table('voucher_profiles')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_business_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_agents_id'), table_name='agents')
    op.drop_index(op.f('ix_agents_business_id'), table_name='agents')
    op.drop_table('agents')
    op.drop_index(op.f('ix_businesses_id'), table_name='businesses')
    op.drop_table('businesses')
    # ### end Alembic commands ###
